=== 0laqase93/DAM1/lenguajes/XSD/nivel2/restriccion/restriccionValores.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tienda">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="mascota" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="especie" type="xs:string"/>
                            <xs:element name="raza" type="xs:string" minOccurs="0"/>
                            <xs:element name="edad" type="xs:decimal"/>
                            <xs:element name="precio" type="xs:decimal"/>
                        </xs:sequence>
                        <xs:attribute name="tipo">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="perro"/>
                                    <xs:enumeration value="gato"/>
                                    <xs:enumeration value="ave"/>
                                    <xs:enumeration value="reptil"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== 0laqase93/DAM1/lenguajes/XSD/nivel2/restriccion/restriccionValores.xml
<?xml version="1.0" encoding="utf-8"?>
<tienda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="restriccionValores.xsd">
    <mascota tipo="perro">
        <nombre>Toby</nombre>
        <especie>Canino</especie>
        <raza>Labrador Retriever</raza>
        <edad>2</edad>
        <precio>500</precio>
    </mascota>
    <mascota tipo="gato">
        <nombre>Luna</nombre>
        <especie>Felino</especie>
        <raza>Siamés</raza>
        <edad>1</edad>
        <precio>300</precio>
    </mascota>
    <mascota tipo="ave">
        <nombre>Periquito</nombre>
        <especie>Psitácido</especie>
        <raza>Común</raza>
        <edad>0.5</edad>
        <precio>20</precio>
    </mascota>
</tienda>
