=== 0laqase93/DAM1/lenguajes/XSD/ejercicioIncremental/03.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="real-estate">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="agencies">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="agency">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="e-mail" type="xs:string"/>
                                        <xs:element name="phone" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="owners">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="owner">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="properties">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="property">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="numberOfFlats" type="xs:positiveInteger"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="flats">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="flat">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="description" type="xs:string"/>
                                        <xs:element name="rate" type="xs:integer"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== 0laqase93/DAM1/lenguajes/XSD (copy 1)/ejercicioIncremental/03.xml
<?xml version="1.0" encoding="UTF-8"?>
<real-estate
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="03.xsd">
	
	<agencies>
        <agency>
            <name>První realitní</name>
            <email>info@realitka.cz</email>
            <phone>+420 481 234 567</phone>
        </agency>
	</agencies>
    
    <owners>
        <owner idOwner="o1">
            <name>Alexandr Kendík</name>
        </owner>
	</owners>
    
    <properties>
        <property idProperty="p1" ownerRef="o1">
            <name>Hearth Residence</name>
            <numberOfFlats>20</numberOfFlats>
        </property>
	</properties>
    
    <flats>
        <flat idFlat="f1" propertyRef="p1" comfortLevel="E" datePosted="2010-12-01">
            <name>K0101</name>
            <description>Small flat with no windows</description>
            <rate>123</rate>
        </flat>
        <flat idFlat="f2" propertyRef="p1" comfortLevel="C">
            <name>K0501</name>
            <description>Ordinary flat with plenty of windows</description>
            <rate>1234</rate>
        </flat>
        <flat idFlat="f3" propertyRef="p1" comfortLevel="A" datePosted="2016-04-01">
            <name>K1501</name>
            <description>Luxury flat with a huge terrace</description>
            <rate>12345</rate>
        </flat>
	</flats>
    
</real-estate>
