=== 0laqase93/DAM1/lenguajes/XSD/ejercicioRandom/inventario.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="inventario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="objeto" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:choice>
                            <xs:element name="mesa">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tipo" type="xs:string" minOccurs="0"/>
                                        
                                        <xs:element name="localizacion" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            
                            <xs:element name="ordenador">
                                <xs:complexType>
                                    <xs:sequence minOccurs="0">
                                        <xs:element name="procesador">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="fabricante" type="xs:string"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        
                                        <xs:element name="memoria">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="unidad" type="xs:string" use="required"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        
                                        <xs:element name="discoduro" type="xs:integer"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                        <xs:attribute name="codigo">
                            <xs:simpleType>
                                <xs:restriction base="xs:ID">
                                    <xs:pattern value="[a-zA-Z]{2}\d{4}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== 0laqase93/DAM1/lenguajes/XSD/ejercicioRandom/inventario.xml
<?xml version="1.0" encoding="UTF-8" ?>
<inventario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="inventario.xsd">
    <objeto codigo="MM2809">
        <mesa>
            <tipo>Oficina</tipo>
            <localizacion>B09</localizacion>
        </mesa>
    </objeto>
    <objeto>
        <ordenador>
            <procesador fabricante="Intel">i3</procesador>
            <memoria unidad="GB">2</memoria>
            <discoduro>520</discoduro>
        </ordenador>
    </objeto>
</inventario>
