=== 0laqase93/DAM1/lenguajes/XSD (copy 1)/ejercicioIncremental/04.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="real-estate">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="agencies">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="agency">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="email" type="xs:string"/>
                                        <xs:element name="phone" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="owners">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="owner">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="idOwner" type="xs:ID" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="properties">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="property">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="numberOfFlats" >
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:maxExclusive value="1501"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="idProperty" type="xs:ID" use="required"/>
                                    <xs:attribute name="ownerRef" type="xs:IDREF" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="flats">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="flat" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:minLength value="5"/>
                                                    <xs:maxLength value="100"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="description" type="xs:string"/>
                                        <xs:element name="rate">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:pattern value="[0-9]*"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="idFlat" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:ID">
                                                <xs:pattern value="[fF][0-9]{1,5}"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="propertyRef" type="xs:IDREF" use="required"/>
                                    <xs:attribute name="comfortLevel">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="[A-F]"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="datePosted" type="xs:string" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== 0laqase93/DAM1/lenguajes/XSD/ejercicioIncremental/04.xml
<?xml version="1.0" encoding="UTF-8"?>
<real-estate
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="04.xsd">
	
	<agencies>
        <agency>
            <name>První realitní</name>
            <email>info@realitka.cz</email>
            <phone>+420 481 234 567</phone>
        </agency>
	</agencies>
    
    <owners>
        <owner idOwner="o1">
            <name>Alexandr Kendík</name>
        </owner>
	</owners>
    
    <properties>
        <property idProperty="p1" ownerRef="o1">
            <name>Hearth Residence</name>
            <numberOfFlats>20</numberOfFlats>
        </property>
	</properties>
    
    <flats>
        <flat idFlat="f1" propertyRef="p1" comfortLevel="E" datePosted="2010-12-01">
            <name>K0101</name>
            <description>Small flat with no windows</description>
            <rate>123</rate>
        </flat>
        <flat idFlat="f2" propertyRef="p1" comfortLevel="C">
            <name>K0501</name>
            <description>Ordinary flat with plenty of windows</description>
            <rate>1234</rate>
        </flat>
        <flat idFlat="f3" propertyRef="p1" comfortLevel="A" datePosted="2016-04-01">
            <name>K1501</name>
            <description>Luxury flat with a huge terrace</description>
            <rate>12345</rate>
        </flat>
	</flats>
</real-estate>
