=== 0laqase93/DAM1/lenguajes/examenXML/damultimate.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema  xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="damultimate">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ordenador" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tipo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Servidor"/>
                                        <xs:enumeration value="Sobremesa"/>
                                        <xs:enumeration value="Portatil"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="componentesSW">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="software" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:choice>
                                                        <xs:element name="sistemaOperativo" type="xs:string"/>
                                                        <xs:element name="aplicacion" type="xs:string"/>
                                                    </xs:choice>
                                                    <xs:element name="version" type="xs:positiveInteger"/>
                                                    <xs:element name="fechaInstalacion" type="xs:date"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="componentesHW">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="hardware" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="tipo" type="xs:string"/>
                                                    <xs:element name="descripcion" type="xs:string"/>
                                                </xs:sequence>
                                                <xs:attribute name="fechaAdquisicion" type="xs:date" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="ActualizacionesRevisiones">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="act" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="descripcion" type="xs:string"/>
                                                    <xs:element name="numActualizacion">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:pattern value="\d{2}\.\d{2}[BF]"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="fechaInstalacion" type="xs:date" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</schema>

=== 0laqase93/DAM1/lenguajes/examenXML/damultimate.xml
<?xml version="1.0" encoding="UTF-8"?>
<damultimate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="damultimate.xsd">
    <ordenador id="or01">
        <tipo>Servidor</tipo>
        <componentesSW>
            <software>
                <sistemaOperativo>Windows</sistemaOperativo>
                <version>10</version>
                <fechaInstalacion>2022-01-01</fechaInstalacion>
            </software>
            <software>
                <aplicacion>Antivirus Avast</aplicacion>
                <version>44</version>
                <fechaInstalacion>2023-02-15</fechaInstalacion>
            </software>
        </componentesSW>
        <componentesHW>
            <hardware fechaAdquisicion="2022-03-10">
                <tipo>CPU</tipo>
                <descripcion>Intel i7</descripcion>
            </hardware>
            <hardware fechaAdquisicion="2022-05-12">
                <tipo>RAM</tipo>
                <descripcion>16GB DDR4</descripcion>
            </hardware>
        </componentesHW>
        <ActualizacionesRevisiones>
            <act fechaInstalacion="2022-04-05">
                <descripcion>Actualización de seguridad</descripcion>
                <numActualizacion>22.04B</numActualizacion>
            </act>
            <act fechaInstalacion="2022-07-15">
                <descripcion>Versión final del software</descripcion>
                <numActualizacion>12.07F</numActualizacion>
            </act>
        </ActualizacionesRevisiones>
    </ordenador>
    <ordenador id="or02">
        <tipo>Sobremesa</tipo>
        <componentesSW>
            <software>
                <sistemaOperativo>Windows</sistemaOperativo>
                <version>11</version>
                <fechaInstalacion>2022-01-01</fechaInstalacion>
            </software>
        </componentesSW>
        <componentesHW/>
        <ActualizacionesRevisiones>
            <act fechaInstalacion="2023-04-05">
                <descripcion>Actualización de seguridad</descripcion>
                <numActualizacion>22.04B</numActualizacion>
            </act>
        </ActualizacionesRevisiones>
    </ordenador>
</damultimate>
