=== 0laqase93/DAM1/lenguajes/XSD/ejercicioSimple2/simple2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Libro">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Titulo" type="xs:string"></xs:element>
                <xs:element name="Autor" type="xs:string"></xs:element>
                <xs:element name="Fecha" type="xs:gYear"></xs:element>
                <xs:element name="ISBN" type="xs:string"></xs:element>
                <xs:element name="Editorial" type="xs:string"></xs:element>
                <xs:element name="color" type="xs:string" default="rojo"></xs:element>
                <xs:element name="ruta">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[A-Za-z]:\\([\w]|[^>:/\\|?*])+(\\([\w]|[^>:/\\|?*])+)*"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== 0laqase93/DAM1/lenguajes/XSD/ejercicioSimple2/simple2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Libro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="simple2.xsd">
    <Titulo>Programming Bye</Titulo>
    <Autor>John C. Smith</Autor>
    <Fecha>2014</Fecha>
    <ISBN>84-202-77678-3</ISBN>
    <Editorial>Mc Graw Hill</Editorial>
    <color>rojo</color>
    <ruta>c:\Mis Documentos\pr√°ctica 1\prueba.txt</ruta>
</Libro>
